# Generated by Django 5.1.4 on 2025-04-23 09:45

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0004_news_image_description_news_location_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='podcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='voice',
            field=models.BooleanField(default=False),
        ),
    ]
