# Generated by Django 5.1.4 on 2025-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0006_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='img/noimage.png', null=True, upload_to='img/'),
        ),
    ]
