# Generated by Django 5.1.4 on 2025-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0007_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='voice_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='voice/'),
        ),
    ]
