# Generated by Django 5.1.4 on 2025-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0008_news_voice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
