# Generated by Django 5.1.4 on 2025-04-28 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0010_alter_reaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'article')},
        ),
        migrations.AddField(
            model_name='reaction',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('session_key', 'article'), ('user', 'article')},
        ),
    ]
