# Generated by Django 5.1.4 on 2025-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0015_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='top_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
