# Generated by Django 5.1.4 on 2025-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0016_news_featured_news_top_news_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='key',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
