# Generated by Django 5.1.4 on 2025-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespeech', '0017_news_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AddField(
            model_name='news',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
    ]
