# Generated by Django 5.1.4 on 2025-06-24 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freespeech", "0018_remove_news_likes_news_opinion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="liked_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="upcoming",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
