# Generated by Django 5.1.4 on 2025-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freespeech", "0019_news_likes_news_upcoming"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
