# Generated by Django 5.2.3 on 2025-06-30 07:47

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freespeech", "0020_news_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="detail_rich_ckeditor",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="upcoming",
            field=models.BooleanField(default=False),
        ),
    ]
