# Generated by Django 5.2.3 on 2025-06-30 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freespeech", "0021_news_detail_rich_ckeditor_news_release_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="upcoming",
        ),
        migrations.AddField(
            model_name="news",
            name="release_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
