# Generated by Django 5.2.3 on 2025-07-05 06:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freespeech", "0023_alter_news_detail_rich_ckeditor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="detail_rich_ckeditor",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default=None, null=True, verbose_name="Content"
            ),
        ),
    ]
